### PR TITLE
Verify bioimageio manifest with --auto-convert

### PR DESCRIPTION
**Pull request by FynnBe**
--auto-convert is a new option that converts model spec changes if automatically possible. This allows for slightly outdated models to pass the validation if no breaking changes have been introduced, because currently the validation is always done expecting the latest format version.

fixed problems with the fru-net_sev_segmentation model:
- [fixed through auto convert]: Authors with name and affiliation
- SPDX licence BSD-3 -> BSD-3-Clause (please confirm)
- exampleImage.npy was missing batch and channel dimension (as documented in model.yaml)

remaining problems with the fru-net_sev_segmentation model:
- [ ] spec 0.3.2 expects `documentation` to be a relative path to a markdown file, thus https://cbia.fi.muni.cz/research/segmentation/fru-net.html is invalid

### CODE REVIEW

**Comment by constantinpape** [comment]
>     * spec 0.3.2 expects `documentation` to be a relative path to a markdown file, thus https://cbia.fi.muni.cz/research/segmentation/fru-net.html is invalid

I think we should change that and also accept html.

**Comment by FynnBe** [comment]
#97 fixes the `documentation` problem for validation (not rendering on the website yet)

**Comment by constantinpape** [comment]
@FynnBe can you rerun the new autoconvert that generates the documentation here?

**Comment by FynnBe** [comment]
> @FynnBe can you rerun the new autoconvert that generates the documentation here?

the autoconvert for now only make the model spec valid (and saving the original content in `config`, but does not write out any generated documentation .md file.
With https://github.com/bioimage-io/spec-bioimage-io/pull/97 merged the tests here should pass (if other `license` issues have been manually fixed like in this PR for one model)

**Comment by FynnBe** [comment]
@esgomezm please approve to run CI

**Pull request merged**
