### PR TITLE
add singleton b and c dims

### PR DESCRIPTION
**Pull request by FynnBe**
added missing batch and channel dimensions to https://github.com/deepimagej/models/blob/master/fru-net_sev_segmentation/resultImage.npy
axes of outputs[0] are described as "byxc"
```python
>>> import numpy
>>> a = numpy.load("resultImage.npy")
>>> a.shape
(1264, 1264)
>>> numpy.save("resultImage.npy", a[None, ..., None])
```

### CODE REVIEW

**Comment by FynnBe** [comment]
No idea if the model actually excepts the input that I modified in the same manner in https://github.com/deepimagej/models/pull/22 and actually produces this 4d output, so you might want to look into that, too.

This will hopefully fix the failing tests in https://github.com/bioimage-io/spec-bioimage-io/blob/master/tests/test_build_spec.py

**Comment by esgomezm** [comment]
Thank you @FynnBe ! I just noticed it today trying Constantin's model. We need to change this in deepImageJ as it saves the example image without considering the batch dimension :(

**Comment by esgomezm** [comment]
A wait! could this one depend on the pre-processing?

**Comment by FynnBe** [comment]
this particular change is influenced by the post-processing I suppose...
test_input -> pre-processing -> nn model -> post-processing -> test_output

But I did change the exampleInput.npy in #22

we really need the dynamic tests, so test_inputs/outputs are actually validated!

**Pull request merged**
